/// <reference types = "cypress" />


describe('Attempt exam on Exam APP',function(){
it  ('Attempt exam and pass the section with passing marks i-e more than 70% and verify the visibility of wrong answered questions on result page' , function() {
    cy.visit('https://exam-template-refactoring.herokuapp.com?examId=63075ad3cb9bde0004366d5a&token=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGVoc2F3YXIuYWxpKzQ2QGFyYmlzb2Z0LmNvbSIsInNjb3BlcyI6WyJWRVJJRklFRCJdfQ.i3HqDp_yy2XIUZLIJL6UbplGF81_FoO9u_XC6fCdBUZIuRonI_JrafhfN1sBVFJziCaYzuk1g5tRgoh_EYez4w')
    cy.url().should('include','/instructions')
    cy.contains('Get Started').click()
    cy.url().should('include','/dashboard')
    cy.get('a[href="/exam/1/intro"]').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('input[value="0"]').click().should('be.checked')
    cy.get('select').select('True').should('have.value','1')
    cy.wait(600)
    cy.contains('Next').click()
    cy.get('input[value="0"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('select').select('False').should('have.value','2')
    cy.contains('Next').click()
    cy.get('input[value="0"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('select').select('Yes').should('have.value','1')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1/submit')
    cy.get('.ekIork').click() //Submit Section Attempt
    cy.url().should('include','/exam/1/result')
    cy.get(':nth-child(1) > .sc-dUWWNf').should('have.text','83%')
    cy.get(':nth-child(1) > .sc-hsOonA').should('have.text','you have passed this section')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','10/12')
    cy.get('.sc-lkwKjF > :nth-child(4)').should('have.text','Question that you did not correctly answer:')
    cy.get('li > p').should('have.text','This is true false drop down')
    cy.get('.sc-jmNpzm > .sc-hjriPb').should('have.text','Overall Exam Progress')
    cy.get('.sc-jmNpzm > .sc-dUWWNf').should('have.text','1/4')
    cy.get('.sc-jmNpzm > .sc-hsOonA').should('have.text','Section Passed')
    cy.contains('Next').click()
    cy.url().should('include','/dashboard')
    cy.get('.sc-ezWOiH').should('have.text','83%')
    cy.get('.sc-cCsOjp').should('have.text','Section Passed')
    //The below command will clear exam section passed
    cy.ClearSection()

    })

it.only('Attempt exam and fail section with marks less than 70 % and verify that user can attempt only wrong answered questions on next attempt' , function() {
    cy.visit('https://exam-template-refactoring.herokuapp.com?examId=63075ad3cb9bde0004366d5a&token=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGVoc2F3YXIuYWxpKzQ2QGFyYmlzb2Z0LmNvbSIsInNjb3BlcyI6WyJWRVJJRklFRCJdfQ.i3HqDp_yy2XIUZLIJL6UbplGF81_FoO9u_XC6fCdBUZIuRonI_JrafhfN1sBVFJziCaYzuk1g5tRgoh_EYez4w')
    cy.url().should('include','/instructions')
    cy.contains('Get Started').click()
    cy.url().should('include','/dashboard')
    cy.get('a[href="/exam/1/intro"]').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('input[value="1"]').click().should('be.checked')
    cy.get('select').select('True').should('have.value','1')
    cy.wait(600)
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[name="3.0"]').should('have.value','0')
    cy.contains('Next').click()
    cy.get('select').select('True').should('have.value','1')
    cy.contains('Next').click()
    cy.get('select').select('Yes').should('have.value','1')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1/submit')
    cy.get('.ekIork').click() //Submit Section Attempt
    cy.url().should('include','/exam/1/result')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-dUWWNf').should('have.text','50%')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-hsOonA').should('have.text','you have not passed this section')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','6/12')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-dUWWNf').should('have.text','2')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-hsOonA').should('have.text','attempts remaining for this section')
    cy.get('.sc-jmNpzm > .sc-hjriPb').should('have.text','Overall Exam Progress')
    cy.get('.sc-jmNpzm > .sc-dUWWNf').should('have.text','0/4')
    cy.get('.sc-jmNpzm > .sc-hsOonA').should('have.text','Section Passed')
    cy.contains('Next').click()
    cy.url().should('include','/dashboard')
    cy.get('.sc-ezWOiH').should('have.text','50%')
    cy.get('.sc-kLLXSd').should('have.text','2 attempts remaining')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').should('have.text','Retake Section')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('.sc-dPyBCJ').should('be.disabled')
    cy.get('input[value="0"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="0"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="0"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('.ekIork').click()
    cy.get(':nth-child(1) > .sc-dUWWNf').should('have.text','100%')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','12/12')
    //The below command will clear exam section passed
    cy.ClearSection()
    })

it  ('Attempt exam and fail the section for available number of attempts and verify loading of lockout period modal' , function() {
    cy.visit('https://exam-template-refactoring.herokuapp.com?examId=63075ad3cb9bde0004366d5a&token=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGVoc2F3YXIuYWxpKzQ2QGFyYmlzb2Z0LmNvbSIsInNjb3BlcyI6WyJWRVJJRklFRCJdfQ.i3HqDp_yy2XIUZLIJL6UbplGF81_FoO9u_XC6fCdBUZIuRonI_JrafhfN1sBVFJziCaYzuk1g5tRgoh_EYez4w')
    cy.url().should('include','/instructions')
    cy.contains('Get Started').click()
    cy.url().should('include','/dashboard')
    cy.get('a[href="/exam/1/intro"]').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('input[value="1"]').click().should('be.checked')
    cy.get('select').select('True').should('have.value','1')
    cy.wait(600)
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('select').select('True').should('have.value','0')
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('select').select('Yes').should('have.value','1')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1/submit')
    cy.get('.ekIork').click() //Submit Section Attempt
    cy.url().should('include','/exam/1/result')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-dUWWNf').should('have.text','50%')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-hsOonA').should('have.text','you have not passed this section')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','6/12')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-dUWWNf').should('have.text','2')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-hsOonA').should('have.text','attempts remaining for this section')
    cy.get('.sc-jmNpzm > .sc-hjriPb').should('have.text','Overall Exam Progress')
    cy.get('.sc-jmNpzm > .sc-dUWWNf').should('have.text','0/4')
    cy.get('.sc-jmNpzm > .sc-hsOonA').should('have.text','Section Passed')
    cy.contains('Next').click()
    cy.url().should('include','/dashboard')
    cy.get('.sc-ezWOiH').should('have.text','50%')
    cy.get('.sc-kLLXSd').should('have.text','2 attempts remaining')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').should('have.text','Retake Section')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('.sc-dPyBCJ').should('be.disabled')
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('.ekIork').click()
    cy.url().should('include','/exam/1/result')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-dUWWNf').should('have.text','50%')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-hsOonA').should('have.text','you have not passed this section')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','6/12')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-dUWWNf').should('have.text','1')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-hsOonA').should('have.text','attempts remaining for this section')
    cy.get('.sc-jmNpzm > .sc-hjriPb').should('have.text','Overall Exam Progress')
    cy.get('.sc-jmNpzm > .sc-dUWWNf').should('have.text','0/4')
    cy.get('.sc-jmNpzm > .sc-hsOonA').should('have.text','Section Passed')
    cy.contains('Next').click()
    cy.url().should('include','/dashboard')
    cy.get('.sc-ezWOiH').should('have.text','50%')
    cy.get('.sc-kLLXSd').should('have.text','1 attempts remaining')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').should('have.text','Retake Section')
    cy.get(':nth-child(1) > a > .sc-ikZpkk').click()
    cy.url().should('include','/exam/1/intro')
    cy.contains('Next').click()
    cy.url().should('include','/exam/1')
    cy.get('.sc-dPyBCJ').should('be.disabled')
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('input[value="1"]').click().should('be.checked')
    cy.contains('Next').click()
    cy.get('.ekIork').click()
    cy.url().should('include','/exam/1/result')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-dUWWNf').should('have.text','50%')
    cy.get(':nth-child(2) > :nth-child(1) > .sc-hsOonA').should('have.text','you have not passed this section')
    cy.get(':nth-child(2) > :nth-child(2) > .sc-dUWWNf').should('have.text','6/12')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-dUWWNf').should('have.text','0')
    cy.get(':nth-child(3) > :nth-child(1) > .sc-hsOonA').should('have.text','attempts remaining for this section')
    cy.get('.sc-jmNpzm > .sc-hjriPb').should('have.text','Overall Exam Progress')
    cy.get('.sc-jmNpzm > .sc-dUWWNf').should('have.text','0/4')
    cy.get('.sc-jmNpzm > .sc-hsOonA').should('have.text','Section Passed')
    cy.contains('Next').click()
    cy.get('.sc-ehmTmK').should('have.text','You didn’t pass the exam')
    cy.get('.sc-lbOyJj').then(($el) => {
         expect($el.text()).to.be.eq("Unfortunately, you've used all 3 attempts and won’t be able to retake the exam for 1 day. You can try again on October 19, 2022. For now, head back to training and learn more about using QuickBooks.")
        })
    cy.visit('https://exam-template-refactoring.herokuapp.com?examId=63075ad3cb9bde0004366d5a&token=Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGVoc2F3YXIuYWxpKzQ2QGFyYmlzb2Z0LmNvbSIsInNjb3BlcyI6WyJWRVJJRklFRCJdfQ.i3HqDp_yy2XIUZLIJL6UbplGF81_FoO9u_XC6fCdBUZIuRonI_JrafhfN1sBVFJziCaYzuk1g5tRgoh_EYez4w')
    cy.url().should('include','/instructions')
    cy.ClearSection()
    })
    



})